### ISSUE TITLE
Debugging Issue

### ISSUE THREAD

**Issue by fuuddanni** [TheM4hd1/PenCrawLer#1]
Do you know how to solve my Issue with Visual Studio 2010. Doesn´t know too much about programming in NET. Error with Dependencies or Package?
![unbenannt](https://user-images.githubusercontent.com/6312269/39083369-7c9f72a2-4563-11e8-862d-28540b4c5a6c.PNG)

**Comment by TheM4hd1** [comment]
Hi, 
Visual Studio 2010 doesn't support String Interpolation
String Interpolation is a feature from VS2015
If you need to run it on vs2010, you have to use another feature like string.format
MSDN:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated
