### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by PacodiazDG** [TheM4hd1/PenCrawLer#3]
https://github.com/TheM4hd1/PenCrawLer/blob/470882f4a38952a38707c94e6e3556e3ab3cf7b1/PeNCrawLer%200.1.0/Forms/FrmSettings.cs#L85

![image](https://user-images.githubusercontent.com/26071783/39089645-2ba955e6-4592-11e8-8ca9-d6e55581a56b.png)

The error occurs when two equal elements are added

**Comment by TheM4hd1** [comment]
Its a dictionary and you're trying to add same keys.
but thanks, i will handle it.
